### ISSUE TITLE
'epson_projector_link' calls `async_add_job`, which is deprecated

### ISSUE THREAD

**Issue by larhedse** [amosyuen/ha-epson-projector-link#107]
Message after latest updated HA 2024.05:

Detected that custom integration 'epson_projector_link' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/epson_projector_link/__init__.py, line 33: hass.async_add_job(, please create a bug report at https://github.com/amosyuen/ha-epson-projector-link/issues

**Comment by amosyuen** [comment]
Resolved in https://github.com/amosyuen/ha-epson-projector-link/releases/tag/v1.0.1
