### ISSUE TITLE
Entity None (<class 'custom_components.epson_projector_link.media_player.EpsonProjectorMediaPlayer'>) is using deprecated supported features

### ISSUE THREAD

**Issue by larhedse** [amosyuen/ha-epson-projector-link#108]
After latest upgrade 2024.05 I get this:

Entity None (<class 'custom_components.epson_projector_link.media_player.EpsonProjectorMediaPlayer'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.TURN_ON|TURN_OFF|SELECT_SOURCE: 2432>, please create a bug report at https://github.com/amosyuen/ha-epson-projector-link/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by amosyuen** [comment]
Resolved in https://github.com/amosyuen/ha-epson-projector-link/releases/tag/v1.0.1
