### ISSUE TITLE
Error with async_get_property when adding a projector

### ISSUE THREAD

**Issue by BjornWill** [amosyuen/ha-epson-projector-link#131]
## Version of the custom_component
Version 1.0.1

## Describe the bug

When adding an Epson projector with TCP support to HA 2024.11.3 through the ha-epson-projector-link integration the following error log produces. I've tried the regular Epson integration which worked on a previous HA VM but that gives the same error. I'm using HA in Container mode through an LXC in Proxmox.

## Debug log

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.epson_projector_link.config_flow
Bron: custom_components/epson_projector_link/config_flow.py:72
integratie: Epson Projector Link (documentatie, problemen)
Eerst voorgekomen: 13:59:33 (1 gebeurtenissen)
Laatst gelogd: 13:59:33

_async_get_property: Unable to connect error: 'Timeout' object does not support the context manager protocol
Traceback (most recent call last):
  File "/root/.homeassistant/custom_components/epson_projector_link/config_flow.py", line 72, in _async_get_property
    return await projector.get_property(property)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.homeassistant/custom_components/epson_projector_link/projector/projector.py", line 174, in get_property
    return await self._send_request(Request(f"{prop}?"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.homeassistant/custom_components/epson_projector_link/projector/projector.py", line 195, in _send_request
    await self.connect()
  File "/root/.homeassistant/custom_components/epson_projector_link/projector/projector.py", line 116, in connect
    with async_timeout.timeout(TIMEOUT_CONNECT):
TypeError: 'Timeout' object does not support the context manager protocol

```

**Comment by squirtbrnr** [comment]
My existing epson projector link integration stopped working today.  I am on HA 2024.10.4.  reloading the integration fails with the error "Unsupported connect response format". Not sure if this is an HTTP connection error or or something else.  This integration worked yesterday 11/30, but no longer works today 12/1.

**Comment by squirtbrnr** [comment]
I got mine working again by cycling power on the unit itself. For some reason port 3629 was closed on the projector. This is the TCP port that uses ESC/VP21 protocol control. Port 4352 which is for PJLINK was open and that was working. After I shut it down with the remote I pulled the power cord for about 30 seconds. I plugged it back in and turned it on and the port was now open. I added the integration and everything works again.

**Comment by larhedse** [comment]
This is just me thinking loud: Could it be that the projector thinks that some software has the connection already and for that reason does not allow yet another software to establish a connection to the projector? That kind of behavior is old-school, since it only allows single active connection at any one time so to speak. However even my APC UPS has the same restriction, and I know that Denon/Marantz Amps/Receivers has the same limitation. Anyway, the only solution if that happens is just the solution you found out squirtbrnr - just restart the device to clear it's memory...

**Comment by BjornWill** [comment]
This was exactly the case, removing power fixed it.

Thanks for your help!
